### PR TITLE
Fix list concat overwriting

### LINKED ISSUE #3166: List concatenation bug
MRE:
```
fruit = [
    "apple",
    "banana",
]

fruit_and_veg = fruit + [
    "edamame",
    "fennel",
]

fruit_veg_and_canned_food = fruit_and_veg + [
    "tuna",
    "baked beans",
]

fruit_veg_canned_food_and_sweets = fruit_veg_and_canned_food + [
    "haribo",
]

fruit_veg_canned_food_and_drinks = fruit_veg_and_canned_food + [
    "matcha latte",
]

fail(', '.join(fruit_veg_canned_food_and_sweets))
```

```
apple, banana, edamame, fennel, tuna, baked beans, matcha latte
```

During the assignment/concatenation of "matcha latte" to the last list, the `fruit_veg_canned_food_and_sweets` list gets modified. There would appear to be something going on here with a shared underlying slice but I can't seem to get to the bottom of it. Also I can't seem to reproduce it with fewer concatenations than the above, weirdly, if anyone was wondering why there are so many.

### PR DESCRIPTION
**Pull request by peterebden**
Fixes #3166 

Looks like this is due to the slices overwriting since on append they both think they have extra capacity, but are in fact sharing it. A pure Go example: https://go.dev/play/p/pLl6MlMr3V4

This fixes this particular case; I don't think there are others at present, we seem to construct lists with capacity equal to their final size in other instances.

### CODE REVIEW

**Review by goddenrich — APPROVED** [review]

**Review by samwestmoreland — APPROVED** [review]
Nice! Thanks for the fix 😄

File: src/parse/asp/objects.go [hunk 1]
```diff
@@ -363,7 +364,7 @@ func (l pyList) Operator(operator Operator, operand pyObject) pyObject {
 			}
 			panic("Cannot add list and " + operand.Type())
 		}
-		return append(l, l2...)
+		return slices.Clip(append(l, l2...))
```
Comment (HartBlanc) [inline src/parse/asp/objects.go:367]: Do we need to apply this change to the `pyFrozenList` case a few lines above too?

Comment (HartBlanc) [inline src/parse/asp/objects.go:367]: Do we need to apply this change to the pyFrozenList case a few lines above too?

**Review by HartBlanc — COMMENTED** [review]
Do we need to apply the slices.Clip to the pyFrozenList case a few lines above too?

File: src/parse/asp/objects.go (hunk 1 above)
Comment (peterebden) [reply src/parse/asp/objects.go:367]: can't hurt, thanks!
