### PR TITLE
Ensure build env is sorted on input to config hash

### LINKED ISSUE #3278: Please often rebuilding when no change was made
Hello,

It seems that please detect changes when none visibly happened.
For example, I build my app, it fetches go toolchain and build the whole thing. Then build the same app, it fetches again the toolchain (not always).

Way to reproduce:

```sh
false; while [ $? -eq 1 ]; do sleep 1; plz build //plugins:go; grep 'Need to rebuild.*' plz-out/log/build.log; done
11:52:47.564 WARNING: Downgrading to Please version 17.11.0 skipped (current version: 17.12.0)
Build finished; total time 50ms, incrementality 100.0%. Outputs:
//plugins:go:
  plz-out/subrepos/plugins/go
11:52:47.571   DEBUG: Need to rebuild //plugins:_go#download, config has changed (was iX483CjwkDTCohF3canxchyXd+o, need iGq7eE29gHhGG7bDW9tj/lLR1Tc)
11:52:47.571   DEBUG: Need to rebuild //plugins:_shell#download, config has changed (was iX483CjwkDTCohF3canxchyXd+o, need iGq7eE29gHhGG7bDW9tj/lLR1Tc)
11:52:47.571   DEBUG: Need to rebuild //plugins:_proto#download, config has changed (was iX483CjwkDTCohF3canxchyXd+o, need iGq7eE29gHhGG7bDW9tj/lLR1Tc)
11:52:47.571   DEBUG: Need to rebuild //plugins:_go_proto#download, config has changed (was iX483CjwkDTCohF3canxchyXd+o, need iGq7eE29gHhGG7bDW9tj/lLR1Tc)
11:52:47.571   DEBUG: Need to rebuild //_please:arcat, config has changed (was iX483CjwkDTCohF3canxchyXd+o, need iGq7eE29gHhGG7bDW9tj/lLR1Tc)
11:52:47.572   DEBUG: Need to rebuild //plugins:_java#download, config has changed (was iX483CjwkDTCohF3canxchyXd+o, need iGq7eE29gHhGG7bDW9tj/lLR1Tc)
11:52:47.579   DEBUG: Need to rebuild //plugins:go_proto, config has changed (was iX483CjwkDTCohF3canxchyXd+o, need iGq7eE29gHhGG7bDW9tj/lLR1Tc)
11:52:47.579   DEBUG: Need to rebuild //plugins:proto, config has changed (was iX483CjwkDTCohF3canxchyXd+o, need iGq7eE29gHhGG7bDW9tj/lLR1Tc)
11:52:47.579   DEBUG: Need to rebuild //plugins:shell, config has changed (was iX483CjwkDTCohF3canxchyXd+o, need iGq7eE29gHhGG7bDW9tj/lLR1Tc)
11:52:47.579   DEBUG: Need to rebuild //plugins:java, config has changed (was iX483CjwkDTCohF3canxchyXd+o, need iGq7eE29gHhGG7bDW9tj/lLR1Tc)
11:52:47.579   DEBUG: Need to rebuild //plugins:go, config has changed (was iX483CjwkDTCohF3canxchyXd+o, need iGq7eE29gHhGG7bDW9tj/lLR1Tc)
11:52:47.589   DEBUG: Need to rebuild ///proto//build_defs:proto_languages, config has changed (was iX483CjwkDTCohF3canxchyXd+o, need iGq7eE29gHhGG7bDW9tj/lLR1Tc)
11:52:47.608   DEBUG: Need to rebuild ///proto//build_defs:grpc_languages, config has changed (was iX483CjwkDTCohF3canxchyXd+o, need iGq7eE29gHhGG7bDW9tj/lLR1Tc)


# Launch again


false; while [ $? -eq 1 ]; do sleep 1; plz build //plugins:go; grep 'Need to rebuild.*' plz-out/log/build.log; done
11:52:53.670 WARNING: Downgrading to Please version 17.11.0 skipped (current version: 17.12.0)
Build finished; total time 30ms, incrementality 100.0%. Outputs:
//plugins:go:
  plz-out/subrepos/plugins/go
11:52:54.707 WARNING: Downgrading to Please version 17.11.0 skipped (current version: 17.12.0)
Build finished; total time 30ms, incrementality 100.0%. Outputs:
//plugins:go:
  plz-out/subrepos/plugins/go
11:52:55.747 WARNING: Downgrading to Please version 17.11.0 skipped (current version: 17.12.0)
Build finished; total time 30ms, incrementality 100.0%. Outputs:
//plugins:go:
  plz-out/subrepos/plugins/go
11:52:56.783 WARNING: Downgrading to Please version 17.11.0 skipped (current version: 17.12.0)
Build finished; total time 20ms, incrementality 100.0%. Outputs:
//plugins:go:
  plz-out/subrepos/plugins/go
11:52:57.823 WARNING: Downgrading to Please version 17.11.0 skipped (current version: 17.12.0)
Build finished; total time 20ms, incrementality 100.0%. Outputs:
//plugins:go:
  plz-out/subrepos/plugins/go
11:52:58.860 WARNING: Downgrading to Please version 17.11.0 skipped (current version: 17.12.0)
Build finished; total time 30ms, incrementality 100.0%. Outputs:
//plugins:go:
  plz-out/subrepos/plugins/go
11:52:59.896 WARNING: Downgrading to Please version 17.11.0 skipped (current version: 17.12.0)
Build finished; total time 30ms, incrementality 100.0%. Outputs:
//plugins:go:
  plz-out/subrepos/plugins/go
11:53:00.944 WARNING: Downgrading to Please version 17.11.0 skipped (current version: 17.12.0)
Build finished; total time 20ms, incrementality 100.0%. Outputs:
//plugins:go:
  plz-out/subrepos/plugins/go
11:53:01.983 WARNING: Downgrading to Please version 17.11.0 skipped (current version: 17.12.0)
Build finished; total time 50ms, incrementality 100.0%. Outputs:
//plugins:go:
  plz-out/subrepos/plugins/go
11:53:01.989   DEBUG: Need to rebuild //plugins:_go_proto#download, config has changed (was iGq7eE29gHhGG7bDW9tj/lLR1Tc, need iX483CjwkDTCohF3canxchyXd+o)
11:53:01.989   DEBUG: Need to rebuild //plugins:_java#download, config has changed (was iGq7eE29gHhGG7bDW9tj/lLR1Tc, need iX483CjwkDTCohF3canxchyXd+o)
11:53:01.989   DEBUG: Need to rebuild //_please:arcat, config has changed (was iGq7eE29gHhGG7bDW9tj/lLR1Tc, need iX483CjwkDTCohF3canxchyXd+o)
11:53:01.989   DEBUG: Need to rebuild //plugins:_proto#download, config has changed (was iGq7eE29gHhGG7bDW9tj/lLR1Tc, need iX483CjwkDTCohF3canxchyXd+o)
11:53:01.989   DEBUG: Need to rebuild //plugins:_shell#download, config has changed (was iGq7eE29gHhGG7bDW9tj/lLR1Tc, need iX483CjwkDTCohF3canxchyXd+o)
11:53:01.989   DEBUG: Need to rebuild //plugins:_go#download, config has changed (was iGq7eE29gHhGG7bDW9tj/lLR1Tc, need iX483CjwkDTCohF3canxchyXd+o)
11:53:01.996   DEBUG: Need to rebuild //plugins:go_proto, config has changed (was iGq7eE29gHhGG7bDW9tj/lLR1Tc, need iX483CjwkDTCohF3canxchyXd+o)
11:53:01.996   DEBUG: Need to rebuild //plugins:java, config has changed (was iGq7eE29gHhGG7bDW9tj/lLR1Tc, need iX483CjwkDTCohF3canxchyXd+o)
11:53:01.996   DEBUG: Need to rebuild //plugins:shell, config has changed (was iGq7eE29gHhGG7bDW9tj/lLR1Tc, need iX483CjwkDTCohF3canxchyXd+o)
11:53:01.996   DEBUG: Need to rebuild //plugins:proto, config has changed (was iGq7eE29gHhGG7bDW9tj/lLR1Tc, need iX483CjwkDTCohF3canxchyXd+o)
11:53:01.996   DEBUG: Need to rebuild //plugins:go, config has changed (was iGq7eE29gHhGG7bDW9tj/lLR1Tc, need iX483CjwkDTCohF3canxchyXd+o)
11:53:02.007   DEBUG: Need to rebuild ///proto//build_defs:proto_languages, config has changed (was iGq7eE29gHhGG7bDW9tj/lLR1Tc, need iX483CjwkDTCohF3canxchyXd+o)
11:53:02.028   DEBUG: Need to rebuild ///proto//build_defs:grpc_languages, config has changed (was iGq7eE29gHhGG7bDW9tj/lLR1Tc, need iX483CjwkDTCohF3canxchyXd+o)
```

Its seems to switch between the same two config hashes (`iX483CjwkDTCohF3canxchyXd+o` and `iGq7eE29gHhGG7bDW9tj/lLR1Tc`).

How is this hash calculated, so I can check if something messes around my env?

Tested with:
* please 17.11.0 and 17.12.0.
* go plugin 1.21.5

### PR DESCRIPTION
**Pull request by peterebden**
Looks like we can get nondeterminism if there are multiple build env vars specified.

Fixes #3278

### CODE REVIEW

File: src/core/config.go [hunk 1]
```diff
@@ -755,9 +757,11 @@ func (config *Configuration) Hash() []byte {
...
 		h.Write([]byte(l))
 	}
-	for _, env := range config.getBuildEnv(false, false) {
-		if !strings.HasPrefix(env, "SECRET") {
-			h.Write([]byte(env))
+	env := config.getBuildEnv(false, false)
+	for _, k := range slices.Sorted(maps.Keys(env)) {
+		if !strings.HasPrefix(k, "SECRET") {
+			h.Write([]byte(k))
+			h.Write([]byte(env[k]))
```
Comment (chrisnovakovic) [inline src/core/config.go:764]: Maybe have a delimiter between them? There's a degenerate case in which two environments could still produce the same hash this way (e.g. `TEST=TEST`, `TES=TTEST`). `=` is probably the safest bet.

Comment (peterebden) [reply src/core/config.go]: Yup, makes sense!

**Review by chrisnovakovic — APPROVED** [review]

**Review by Tatskaari — APPROVED** [review]
Got there before me
